import Foundation

public struct StructureFileWriter: Sendable {
    public init() {}

    public func pdb(_ structure: MolecularStructure) -> Data {
        var lines: [String] = ["REMARK   Generated by MoleculePad"]
        for atom in structure.atoms {
            let record = atom.isHetero ? "HETATM" : "ATOM  "
            let chain = String(atom.chainID.prefix(1)).isEmpty ? " " : String(atom.chainID.prefix(1))
            let element = ElementTable.normalized(atom.element)
            lines.append(String(
                format: "%@%5d %-4@ %-3@ %@%4d    %8.3f%8.3f%8.3f%6.2f%6.2f          %2@",
                record, min(99_999, max(1, atom.serial)), atom.name as NSString,
                atom.residueName as NSString, chain as NSString,
                atom.residueNumber, atom.position.x, atom.position.y, atom.position.z,
                atom.occupancy, atom.bFactor, element as NSString
            ))
        }
        for bond in structure.bonds {
            guard let first = structure.atoms.first(where: { $0.id == bond.atom1 }),
                  let second = structure.atoms.first(where: { $0.id == bond.atom2 }) else { continue }
            lines.append(String(format: "CONECT%5d%5d", first.serial, second.serial))
        }
        lines.append("END")
        return Data((lines.joined(separator: "\n") + "\n").utf8)
    }
}
